on:
  push:
    branches:
      - feature/pipeline-rewrite
    # paths:
    #   - "frontend/**"

name: Deploy frontend
env:
  PATHS: "/*"
  SOURCE_DIR: "./frontend/build"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  working-directory: "./frontend"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Dependencies
        working-directory: ${{ env.working-directory }}
        run: npm ci --no-audits

      - name: Lint
        working-directory: ${{ env.working-directory }}
        run: npm run lint

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: npm run build
        env:
          REACT_APP_API_URL: "https://di5ds1eotmbx1.cloudfront.net/"

      - name: Deploy to S3 Staging
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}

      - name: Invalidate Cloudfront Staging
        uses: muratiger/invalidate-cloudfront-and-wait-for-completion-action@master
        env:
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID_PROD }}
